draft: Get physical
konstructio/colony pull request #13
Opened 2024-11-01 02:04 UTC by jarededwards

## Description

## Related Issue(s)

Fixes #

## How to test

2024-11-01 02:29 UTC, patrickdappollonio requested changes
It's always correct to return wrapped errors (that is, the value is `err` and the string contains `%w` otherwise errors become incomparable and undebuggeable.

I think the linter should've picked that up. If not, I'll try to fix it first time I'm back.

2024-11-01 02:29 UTC, patrickdappollonio commented on cmd/destroy.go
> +				return fmt.Errorf("error creating docker client: %v ", err.Error())
```suggestion
				return fmt.Errorf("error creating docker client: %w ", err)
```

Always wrap errors, don't convert them to string.

2024-11-01 02:29 UTC, patrickdappollonio commented on cmd/destroy.go
> +				return fmt.Errorf("error: %v", err.Error())
Same as above

2024-11-01 02:29 UTC, patrickdappollonio commented on cmd/destroy.go
> +				return fmt.Errorf("error removing file: %v ", err.Error())
Same as above

2024-11-01 02:29 UTC, patrickdappollonio commented on cmd/destroy.go
> +			err = os.Remove(constants.KubeconfigHostPath)
This might not need a check... Unless you really want the failure.

For example, this would fail if the file you're trying to delete doesn't exist...

But it would also fail if you can't "lock" the file for writing (say, another process has a hold of it).

Two very different errors that might need to be handled differently if need be 😆

2024-11-01 02:29 UTC, patrickdappollonio commented on cmd/init.go
> +				return fmt.Errorf("error validating colony api key: %s %v \n visit https://colony.konstruct.io to get a valid api key", apiKey, err.Error())
Errors should be wrapped. Not returned as string. Calling `.Error()` on an error effectively converts it to a string.

2024-11-01 02:29 UTC, patrickdappollonio commented on cmd/init.go
> +				return fmt.Errorf("error creating docker client: %v ", err.Error())
😆 Not a fan the error was changed from wrapped to string 🤣🤣🤣

2024-11-01 02:29 UTC, patrickdappollonio commented on cmd/init.go
> +				return fmt.Errorf("error creating container: %v ", err.Error())
Errors should be wrapped. Not returned as string. Calling `.Error()` on an error effectively converts it to a string.

2024-11-01 02:29 UTC, patrickdappollonio commented on cmd/init.go
> +				return fmt.Errorf("error creating Kubernetes client: %v ", err.Error())
Errors should be wrapped. Not returned as string. Calling `.Error()` on an error effectively converts it to a string.

2024-11-01 02:29 UTC, patrickdappollonio commented on cmd/init.go
> +				return fmt.Errorf("error finding coredns deployment: %v ", err.Error())
Errors should be wrapped. Not returned as string. Calling `.Error()` on an error effectively converts it to a string.

2024-11-01 02:29 UTC, patrickdappollonio commented on cmd/init.go
> +				return fmt.Errorf("error finding metrics-server deployment: %v ", err.Error())
Errors should be wrapped. Not returned as string. Calling `.Error()` on an error effectively converts it to a string.

2024-11-01 02:29 UTC, patrickdappollonio commented on cmd/init.go
> +			time.Sleep(time.Second * 9)
Any thought on why 9 and not 10? 12? 😆

It would be good to standardize in a number. If the number isn't good enough, it would be better then to try a condition and time out if you go above a certain threshold.

2024-11-01 02:29 UTC, patrickdappollonio commented on cmd/init.go
> +				return fmt.Errorf("error finding hegel deployment: %v ", err.Error())
Errors should be wrapped. Not returned as string. Calling `.Error()` on an error effectively converts it to a string.

2024-11-01 02:29 UTC, patrickdappollonio commented on cmd/init.go
> +				return fmt.Errorf("error finding rufio deployment: %v ", err.Error())
Errors should be wrapped. Not returned as string. Calling `.Error()` on an error effectively converts it to a string.

2024-11-01 02:29 UTC, patrickdappollonio commented on cmd/init.go
> +				return fmt.Errorf("error finding smee deployment: %v ", err.Error())
Errors should be wrapped. Not returned as string. Calling `.Error()` on an error effectively converts it to a string.

2024-11-01 02:29 UTC, patrickdappollonio commented on cmd/init.go
> +				return fmt.Errorf("error finding tink-server deployment: %v ", err.Error())
Errors should be wrapped. Not returned as string. Calling `.Error()` on an error effectively converts it to a string.

2024-11-01 02:29 UTC, patrickdappollonio commented on cmd/init.go
> +				return fmt.Errorf("error finding tink-controller deployment: %v ", err.Error())
Errors should be wrapped. Not returned as string. Calling `.Error()` on an error effectively converts it to a string.

2024-11-01 02:29 UTC, patrickdappollonio commented on cmd/init.go
> +				return fmt.Errorf("error creating secret: %w", err)
Props for this one! 🎉😆

2024-11-01 02:29 UTC, patrickdappollonio commented on internal/docker/docker.go
> +	return "", "", fmt.Errorf("container %s not found", constants.ColonyK3sContainerName)
```suggestion
	return "", "", fmt.Errorf("container %q not found", constants.ColonyK3sContainerName)
```

`%q` is always better and can escape unsafe sequences 😄

2024-11-01 02:29 UTC, patrickdappollonio commented on internal/docker/docker.go
> +		return fmt.Errorf("error getting %s container: %v", constants.ColonyK3sContainerName, err)
Errors should be wrapped. Not returned as string. Calling `.Error()` on an error effectively converts it to a string.

Also, `%q`

2024-11-01 02:29 UTC, patrickdappollonio commented on internal/docker/docker.go
> +		return fmt.Errorf("error removing container: %v", err)
Errors should be wrapped. Not returned as string. Calling `.Error()` on an error effectively converts it to a string. (`%v` does the same thing; also, how come there's 4 ways to render errors! 😆)

2024-11-01 02:29 UTC, patrickdappollonio commented on internal/docker/docker.go
> +	colonyK3sContainerID, _, _ := getColonyK3sContainerIDAndName(ctx, c)
Wouldn't this eat any error like the docker daemon being in a bad state?

I feel we would want to know those things.

2024-11-01 02:29 UTC, patrickdappollonio commented on internal/docker/docker.go
> +	c.log.Info(fmt.Sprintf("found container name %s with ID %s  ", strings.TrimPrefix(colonyK3sContainerName, "/"), colonyK3sContainerID[:constants.DefaultDockerIDLength]))
This could point to a position on the string that doesn't exist. Needs to be checked for bounds.

2024-11-01 02:29 UTC, patrickdappollonio commented on internal/docker/docker.go
> +		return fmt.Errorf("%s container already exists. please remove before continuing or run `colony destroy`", constants.ColonyK3sContainerName)
```suggestion
		return fmt.Errorf("%q container already exists. please remove before continuing or run `colony destroy`", constants.ColonyK3sContainerName)
```

2024-11-01 02:29 UTC, patrickdappollonio commented on internal/docker/docker.go
> +	if err != nil {
So if this fails, the error is printed but the code continues 🤔

2024-11-01 02:29 UTC, patrickdappollonio commented on internal/docker/docker.go
> +	if err != nil {
If we can't get a current working directory this fails, the error gets printed and the code still continues, but `pwd` is assumed to have something 🤔

2024-11-01 02:29 UTC, patrickdappollonio commented on internal/docker/docker.go
> +	if err != nil {
So if the container creation fails, the error is rendered but the code continues 🤔

2024-11-01 02:29 UTC, patrickdappollonio commented on internal/docker/docker.go
> +func waitForKubeconfig(filename string, interval time.Duration) {
Might consider using Kubernetes' own `wait.PollImmediate` instead of maintaining yet another copy of a "wait function". @jokestax has written it a handful of times and might be able to help!

Also, your code above has a context that can be cancelled. You can have that in consideration when doing the infinite for loop, the same way as you consider the duration timeout.

2024-11-01 02:29 UTC, patrickdappollonio commented on internal/docker/docker.go
> +	waitForKubeconfig(fmt.Sprintf("./%s", constants.KubeconfigHostPath), waitInterval)
This function should return an error that should be handled here. If not, it will simply error out but continue execution.

2024-11-01 02:29 UTC, patrickdappollonio commented on internal/docker/docker.go
> +			fmt.Printf("error checking file: %v\n", err)
This relates to the comment above about handling and returning errors.

2024-11-01 02:29 UTC, patrickdappollonio commented on internal/k8s/k8s.go
> +		return nil, fmt.Errorf("error creating kubernetes client: %s", err.Error())
I know someone wrote the string before, but this is doubling down on a bad practice 😆

2024-11-01 02:29 UTC, patrickdappollonio commented on internal/k8s/k8s.go
> +		return nil, fmt.Errorf("error creating dynamic client: %s", err.Error())
Errors should be wrapped. Not returned as string. Calling `.Error()` on an error effectively converts it to a string.

2024-11-01 02:29 UTC, patrickdappollonio commented on internal/k8s/k8s.go
> +		return nil, fmt.Errorf("error creating discovery client: %s", err.Error())
Errors should be wrapped. Not returned as string. Calling `.Error()` on an error effectively converts it to a string.

2024-11-01 02:29 UTC, patrickdappollonio commented on internal/k8s/k8s.go
> +		return nil, fmt.Errorf("error getting API group resources: %s", err.Error())
Errors should be wrapped. Not returned as string. Calling `.Error()` on an error effectively converts it to a string.

2024-11-01 02:29 UTC, patrickdappollonio commented on internal/k8s/k8s.go
> +		return fmt.Errorf("error creating secret: %v ", err.Error())
😑

The previous code is less buggy 😆

2024-11-01 02:29 UTC, patrickdappollonio commented on internal/k8s/k8s.go
> +			return fmt.Errorf("error decoding manifest: %v ", err.Error())
Previous code is preferred.

2024-11-01 02:29 UTC, patrickdappollonio commented on internal/k8s/k8s.go
> +			return fmt.Errorf("unable to map manifest to a Kubernetes resource: %v ", err.Error())
Previous code preferred.

2024-11-01 02:29 UTC, patrickdappollonio commented on internal/k8s/k8s.go
> +	"k8s.io/apimachinery/pkg/util/wait"
Someone imported wait here yet didn't use it to wait for the kubeconfig above!? 😆

2024-11-01 02:29 UTC, patrickdappollonio commented on internal/k8s/k8s.go
> +					return fmt.Errorf("error updating resource: %v ", retryErr.Error())
Errors should be wrapped. Not returned as string. Calling `.Error()` on an error effectively converts it to a string.

Prior code is better!

2024-11-01 02:29 UTC, patrickdappollonio commented on internal/k8s/k8s.go
> +			return fmt.Errorf("error creating resource: %v ", err.Error())
Prior code is better!

2024-11-01 02:29 UTC, patrickdappollonio commented on internal/k8s/k8s.go
> +	log := logger.New(logger.Debug)
Second time I see this line. Must be seeing things 😆

Jokes aside, the app should create a logger that everyone below should use how it was created. Having to recreate the logger on every function defeats the purpose of having a logger with levels to begin with (because each function can choose what level to log, instead of leaving that to the app!)

I'm okay merging this line but we should change that in the future.

2024-11-01 02:29 UTC, patrickdappollonio commented on internal/k8s/k8s.go
> +			return false, fmt.Errorf("error listing statefulsets: %v ", err.Error())
Errors should be wrapped. Not returned as string. Calling `.Error()` on an error effectively converts it to a string.

2024-11-01 02:29 UTC, patrickdappollonio commented on internal/k8s/k8s.go
> +		return false, fmt.Errorf("the Deployment %q in Namespace %q was not ready within the timeout period: %v ", deploymentName, namespace, err.Error())
Errors should be wrapped. Not returned as string. Calling `.Error()` on an error effectively converts it to a string.

2024-11-01 02:29 UTC, patrickdappollonio commented on internal/k8s/k8s.go
> +			return false, fmt.Errorf("error getting Deployment: %v ", err.Error())
Errors should be wrapped. Not returned as string. Calling `.Error()` on an error effectively converts it to a string.

2024-11-01 02:29 UTC, patrickdappollonio commented on internal/k8s/k8s.go
> +		return nil, fmt.Errorf("error waiting for Deployment: %v ", err.Error())
Errors should be wrapped. Not returned as string. Calling `.Error()` on an error effectively converts it to a string.

2024-11-04 18:43 UTC, jarededwards commented on cmd/destroy.go
> +			err = os.Remove(constants.KubeconfigHostPath)
i added a check to see if the file exists, if it does delete otherwise continue (they may have moved it and consumed it)

2024-11-04 18:48 UTC, jarededwards commented on cmd/init.go
> +			time.Sleep(time.Second * 9)
this was a debug, douglas helped us discover the discovery of the restmapper only contains api resources at time of initialization and we needed to reinitialize the client after the new crds from tink-stack were available in the cluster. removed this sleep

2024-11-04 19:34 UTC, patrickdappollonio commented on cmd/destroy.go
> +}
I really think that you should do a function like this instead:

```go
func deleteFile(location string) error) {
    if err := os.Remove(location); err != nil && ! os.IsNotExists(err) {
        return fmt.Errorf("file %q couldn't be deleted: %w", location, err) 
   } 
} 
```

This will complain if and only if an error other than "file not found" exists... And those are the kind of silent issues that we have in abundance 😆

2024-11-04 19:35 UTC, patrickdappollonio commented on cmd/destroy.go
> +}
Sorry for the format. On mobile.

2024-11-04 19:35 UTC, patrickdappollonio commented on internal/colony/api.go
> +		return fmt.Errorf("error creating request: %w ", err)
```suggestion
		return fmt.Errorf("error creating request: %w", err)
```

2024-11-04 19:35 UTC, patrickdappollonio commented on internal/colony/api.go
> +		return fmt.Errorf("error making request: %w ", err)
```suggestion
		return fmt.Errorf("error making request: %w", err)
```

2024-11-04 19:35 UTC, patrickdappollonio commented on internal/colony/api.go
> +		return fmt.Errorf("error decoding response: %w ", err)
```suggestion
		return fmt.Errorf("error decoding response: %w", err)
```

2024-11-04 19:36 UTC, patrickdappollonio commented on internal/colony/api.go
> +		return nil, fmt.Errorf("error creating request: %w ", err)
```suggestion
		return nil, fmt.Errorf("error creating request: %w", err)
```

2024-11-04 19:36 UTC, patrickdappollonio commented on internal/colony/api.go
> +		return nil, fmt.Errorf("error making request: %w ", err)
```suggestion
		return nil, fmt.Errorf("error making request: %w", err)
```

2024-11-04 19:37 UTC, patrickdappollonio commented on internal/colony/api.go
> +		return nil, fmt.Errorf("error decoding response: %w ", err)
```suggestion
		return nil, fmt.Errorf("error decoding response: %w", err)
```

2024-11-04 19:38 UTC, patrickdappollonio commented on internal/docker/docker.go
> +		if container.Names[0] == "/"+constants.ColonyK3sContainerName {
Needs to check if there's at least one name in the container. Otherwise `Names[0]` will crash the app.

2024-11-04 19:39 UTC, patrickdappollonio commented on internal/docker/docker.go
> +	defer c.cli.Close()
Might want to expose this in your object... Otherwise this client can be used exactly once. Every follow up call will fail due to the client being already closed.

2024-11-04 19:39 UTC, patrickdappollonio commented on internal/docker/docker.go
> +		return fmt.Errorf("error getting %q container: %w ", constants.ColonyK3sContainerName, err)
```suggestion
		return fmt.Errorf("error getting %q container: %w", constants.ColonyK3sContainerName, err)
```

2024-11-04 19:40 UTC, patrickdappollonio commented on internal/docker/docker.go
> +	c.log.Info(fmt.Sprintf("found container name %q with ID %q  ", strings.TrimPrefix(colonyK3sContainerName, "/"), colonyK3sContainerID[:constants.DefaultDockerIDLength]))
```suggestion
	c.log.Info(fmt.Sprintf("found container name %q with ID %q", strings.TrimPrefix(colonyK3sContainerName, "/"), colonyK3sContainerID[:constants.DefaultDockerIDLength]))
```

2024-11-04 19:40 UTC, patrickdappollonio commented on internal/docker/docker.go
> +		return fmt.Errorf("error removing container: %w ", err)
```suggestion
		return fmt.Errorf("error removing container: %w", err)
```

2024-11-04 19:41 UTC, patrickdappollonio commented on internal/docker/docker.go
> +		return fmt.Errorf("error getting %q container: %w ", constants.ColonyK3sContainerName, err)
```suggestion
		return fmt.Errorf("error getting %q container: %w", constants.ColonyK3sContainerName, err)
```

2024-11-04 19:41 UTC, patrickdappollonio commented on internal/docker/docker.go
> +		return fmt.Errorf("error pulling image %q: %w ", imageName, err)
```suggestion
		return fmt.Errorf("error pulling image %q: %w", imageName, err)
```

2024-11-04 19:42 UTC, patrickdappollonio commented on internal/docker/docker.go
> +		return fmt.Errorf("error getting current working directory: %w ", err)
```suggestion
		return fmt.Errorf("error getting current working directory: %w", err)
```

2024-11-04 19:43 UTC, patrickdappollonio commented on internal/docker/docker.go
> +			Source: fmt.Sprintf("%s/laptop/k3s-bootstrap/colony.yaml", pwd),
Not to fix now... But it's both unsafe and incorrect concatenating paths using string formats. The proper and secure way is `filepath.Join(pwd, "/laptop/k3s-bootstrap/colony.yaml")`

Plus it gets us closer to windows support 😆

2024-11-04 19:44 UTC, patrickdappollonio commented on internal/docker/docker.go
> +				return fmt.Errorf("error checking file: %v", err)
```suggestion
				return fmt.Errorf("error checking file: %w", err)
```

2024-11-04 19:45 UTC, patrickdappollonio commented on internal/k8s/k8s.go
> +		return nil, fmt.Errorf("error creating kubernetes client: %w ", err)
```suggestion
		return nil, fmt.Errorf("error creating kubernetes client: %w", err)
```

2024-11-04 19:45 UTC, patrickdappollonio commented on internal/k8s/k8s.go
> +		return nil, fmt.Errorf("error creating dynamic client: %w ", err)
```suggestion
		return nil, fmt.Errorf("error creating dynamic client: %w", err)
```

2024-11-04 19:45 UTC, patrickdappollonio commented on internal/k8s/k8s.go
> +		return nil, fmt.Errorf("error creating discovery client: %w ", err)
```suggestion
		return nil, fmt.Errorf("error creating discovery client: %w", err)
```

2024-11-04 19:46 UTC, patrickdappollonio commented on internal/k8s/k8s.go
> +		return nil, fmt.Errorf("error getting API group resources: %w ", err)
```suggestion
		return nil, fmt.Errorf("error getting API group resources: %w", err)
```

2024-11-04 19:46 UTC, patrickdappollonio commented on internal/k8s/k8s.go
> +		return fmt.Errorf("error creating secret: %w ", err)
```suggestion
		return fmt.Errorf("error creating secret: %w", err)
```

2024-11-04 19:48 UTC, patrickdappollonio commented on internal/docker/docker.go
> +	c.log.Info(fmt.Sprintf("found container name %q with ID %q  ", strings.TrimPrefix(colonyK3sContainerName, "/"), colonyK3sContainerID[:constants.DefaultDockerIDLength]))
iirc the logger has a "printf" style formatter

```suggestion
	c.log.Infof("found container name %q with ID %q  ", strings.TrimPrefix(colonyK3sContainerName, "/"), colonyK3sContainerID[:constants.DefaultDockerIDLength])
```

2024-11-04 19:49 UTC, patrickdappollonio commented on internal/k8s/k8s.go
> +		return fmt.Errorf("error creating secret: %w ", err)
```suggestion
		return fmt.Errorf("error creating secret: %w", err)
```

2024-11-04 19:49 UTC, patrickdappollonio commented on internal/k8s/k8s.go
> +			return fmt.Errorf("error decoding manifest: %w ", err)
```suggestion
			return fmt.Errorf("error decoding manifest: %w", err)
```

2024-11-04 19:49 UTC, patrickdappollonio commented on internal/k8s/k8s.go
> +			return fmt.Errorf("unable to map manifest to a Kubernetes resource: %w ", err)
```suggestion
			return fmt.Errorf("unable to map manifest to a Kubernetes resource: %w", err)
```

2024-11-04 19:49 UTC, patrickdappollonio commented on internal/k8s/k8s.go
> +					return fmt.Errorf("error updating resource: %w ", retryErr)
```suggestion
					return fmt.Errorf("error updating resource: %w", retryErr)
```

2024-11-04 19:50 UTC, patrickdappollonio commented on internal/k8s/k8s.go
> +	log.Info(fmt.Sprintf("waiting for deployment %q in namespace %q to be ready - this could take up to %d seconds", deploymentName, namespace, timeoutSeconds))
```suggestion
	log.Infof("waiting for deployment %q in namespace %q to be ready - this could take up to %d seconds", deploymentName, namespace, timeoutSeconds)
```

2024-11-04 19:52 UTC, patrickdappollonio commented on internal/k8s/k8s.go
> +				log.Warn("connection error, retrying: %w ", err)
😆 I see what you did here. However `%w` doesn't work on anything other than error "handling". This is sending it to a logger, not handling the error so I would be really surprised if `%w` is supported.

```suggestion
				log.Warn("connection error, retrying: %s", err)
```

2024-11-04 19:52 UTC, patrickdappollonio commented on internal/k8s/k8s.go
> +			log.Info(fmt.Sprintf("all pods in deployment %q are ready", deploymentName))
```suggestion
			log.Infof("all pods in deployment %q are ready", deploymentName)
```

2024-11-04 19:52 UTC, patrickdappollonio commented on internal/k8s/k8s.go
> +		return false, fmt.Errorf("the Deployment %q in Namespace %q was not ready within the timeout period: %w ", deploymentName, namespace, err)
```suggestion
		return false, fmt.Errorf("the Deployment %q in Namespace %q was not ready within the timeout period: %w", deploymentName, namespace, err)
```

2024-11-04 19:53 UTC, patrickdappollonio commented on internal/k8s/k8s.go
> +			return false, fmt.Errorf("error getting Deployment: %w ", err)
```suggestion
			return false, fmt.Errorf("error getting Deployment: %w", err)
```

2024-11-05 02:07 UTC, jarededwards commented on internal/k8s/k8s.go
> +	log := logger.New(logger.Debug)
i worked with rishi on this and updated! thanks! 🫶

2024-11-05 21:58 UTC, patrickdappollonio requested changes

2024-11-05 21:58 UTC, patrickdappollonio commented on internal/k8s/k8s.go
> +		context.TODO(),
```suggestion
		ctx, 
```

You have a context in the parent function, how come you don't want to use it here?

2024-11-07 03:02 UTC, jarededwards commented on internal/k8s/k8s.go
> +		context.TODO(),
but i do! :D

2024-11-11 19:28 UTC, patrickdappollonio requested changes

2024-11-11 19:28 UTC, patrickdappollonio commented on cmd/destroy.go
> +}
Would probably move this off from `cmd/destroy.go` to a place where it makes a bit more sense.

2024-11-11 19:28 UTC, patrickdappollonio commented on cmd/init.go
> +
```suggestion
```

Might want to enable `gofumpt` 😄

2024-11-11 19:28 UTC, patrickdappollonio commented on cmd/init.go
> +			k8sClient.WaitForDeploymentReady(ctx, coreDNSDeployment, 120)
This seems like the kind of thing that would return an error...

2024-11-11 19:28 UTC, patrickdappollonio commented on cmd/init.go
> +			k8sconfig, err := ioutil.ReadFile(constants.KubeconfigHostPath)
```suggestion
			k8sconfig, err := os.ReadFile(constants.KubeconfigHostPath)
```

The `ioutil` package is deprecated.

2024-11-11 19:28 UTC, patrickdappollonio commented on cmd/init.go
> +			k8sClient.WaitForDeploymentReady(ctx, metricsServerDeployment, 120)
Missing error handling here as well.

2024-11-11 19:28 UTC, patrickdappollonio commented on cmd/init.go
> +			k8sClient.WaitForDeploymentReady(ctx, colonyAgentDeployment, 120)
Missing error handling here as well.

2024-11-11 19:28 UTC, patrickdappollonio commented on cmd/init.go
> +			k8sClient.WaitForDeploymentReady(ctx, hegelDeployment, 120)
Missing error handling here as well.

2024-11-11 19:28 UTC, patrickdappollonio commented on cmd/init.go
> +			k8sClient.WaitForDeploymentReady(ctx, smeeDeployment, 120)
Missing error handling here as well.

2024-11-11 19:28 UTC, patrickdappollonio commented on cmd/init.go
> +			k8sClient.WaitForDeploymentReady(ctx, tinkServerDeployment, 120)
Missing error handling here as well.

2024-11-11 19:28 UTC, patrickdappollonio commented on cmd/init.go
> +			k8sClient.WaitForDeploymentReady(ctx, tinkControllerDeployment, 120)
Missing error handling here as well.

2024-11-11 19:28 UTC, patrickdappollonio commented on cmd/init.go
> +				url := fmt.Sprintf("https://raw.githubusercontent.com/jarededwards/k3s-datacenter/refs/heads/main/templates/%s", template)
I assume this would go somewhere else, since this is pointed to your account @jarededwards

2024-11-11 19:28 UTC, patrickdappollonio commented on cmd/init.go
> +				filename := filepath.Join(pwd, "templates/"+template)
```suggestion
				filename := filepath.Join(pwd, "templates", template)
```

No need to concat like that 😄 You can pass multiple parameters to `filepath.Join()`

2024-11-11 19:28 UTC, patrickdappollonio commented on cmd/init.go
> +				fmt.Println(filename)
This seems like quite a random `fmt.Println()`, and doesn't use the logger. Perhaps changing it to a logger?

```suggestion
				log.Infof("downloading into:", filename)
```

2024-11-11 19:28 UTC, patrickdappollonio commented on cmd/init.go
> +	cmd.Flags().StringVar(&loadBalancerInterface, "loadBalancerInterface", "eth0", "the local network interface for colony to use (required)")
To actually mark things as required, you don't need to write those here as part of the description.

See: https://pkg.go.dev/github.com/spf13/cobra#MarkFlagRequired

Also, we really need to make flags to be posix compliant (so snake case instead of camel case):

```
--api-url vs --apiURL
--load-balancer-interface vs --loadBalancerInterface
```

2024-11-11 19:28 UTC, patrickdappollonio commented on cmd/init.go
> +}
There's a bit of a better way to do this, mainly because this could fail if the parent directory doesn't exist.

You know how there's `mkdir` and `mkdir -p` on Linux? Go has the same: `os.Mkdir()` (which fails if the parent doesn't exist) and [`os.MkdirAll()`](https://pkg.go.dev/os#MkdirAll) (which attempts to create the entire path you give to it)

```suggestion
func createDirIfNotExist(dir string) error {
	if err := os.MkdirAll(dir, 0755); err != nil {
	    return fmt.Errorf("unable to create directory %q: %w", dir, err)
	}
	return nil
}
```

2024-11-11 19:28 UTC, patrickdappollonio commented on cmd/init.go
> +	files, err := ioutil.ReadDir(dir)
```suggestion
	files, err := os.ReadDir(dir)
```

`ioutil` is deprecated.

2024-11-11 19:28 UTC, patrickdappollonio commented on cmd/init.go
> +			content, err := ioutil.ReadFile(filePath) // Read file content
```suggestion
			content, err := os.ReadFile(filePath) // Read file content
```

`ioutil` is deprecated.

2024-11-11 19:28 UTC, patrickdappollonio commented on internal/docker/docker.go
> +}
Curious why _just this function_ isn't part of the `Client` object:

```suggestion
func (c *Client) getColonyK3sContainer(ctx context.Context) (*types.Container, error) {

	containers, err := c.cli.ContainerList(ctx, containerTypes.ListOptions{All: true})
	if err != nil {
		return nil, fmt.Errorf("error listing containers on host: %w", err)
	}

	for _, container := range containers {
		if len(container.Names) > 0 && container.Names[0] == "/"+constants.ColonyK3sContainerName {
			return &container, nil
		}
	}
	return nil, ErrK3sContainerNotFound
}
```

It's a one-liner 😄

2024-11-11 19:28 UTC, patrickdappollonio commented on internal/docker/docker.go
> +	defer c.cli.Close()
Still think this is super important. Closing here means that you cannot reuse `Client` anywhere else unless you create it from scratch.

2024-11-11 19:28 UTC, patrickdappollonio commented on internal/docker/docker.go
> +	c.log.Infof("found container name %q with ID %q", strings.TrimPrefix(k3scontainer.Names[0], "/"), k3scontainer.ID[:constants.DefaultDockerIDLength])
Still think this could break your program because `k3scontainer.Names` doesn't have any values or because `k3scontainer.ID`'s string length is less than `constants.DefaultDockerIDLength`. Both are unbound memory accesses that should be checked to prevent a nil panic.

2024-11-11 19:28 UTC, patrickdappollonio commented on internal/docker/docker.go
> +				fmt.Printf("unable to delete volume %s", err)
Logger here perhaps instead of printing to `stdout`?

2024-11-11 19:28 UTC, patrickdappollonio commented on internal/docker/docker.go
> +	defer c.cli.Close()
This seems arbitrarily placed in the middle of a few operations. How come?

2024-11-11 19:28 UTC, patrickdappollonio commented on internal/docker/docker.go
> +	if err != nil {
This needs to be addressed too.

2024-11-11 19:28 UTC, patrickdappollonio commented on internal/docker/docker.go
> +		panic(err)
... 😆

2024-11-11 19:28 UTC, patrickdappollonio commented on internal/docker/docker.go
> +	log.Infof("Checking for file %s every %d...\n", filepath.Join(pwd, constants.KubeconfigHostPath), waitInterval)
Log lines should never end on a new line. That's because the logger can be replaced for a structured logger, a JSON logger, a remote logger or everything in between.

```suggestion
	log.Infof("Checking for file %s every %d...", filepath.Join(pwd, constants.KubeconfigHostPath), waitInterval)
```

2024-11-11 19:28 UTC, patrickdappollonio commented on internal/docker/docker.go
> +}
This code has a bug: having a `sleep` inside the `default` case means you really aren't yielding to the timeout (from `<-timeoutCh`) until `interval` has been completed. 

We could fix this function if we use a ticker to check every N seconds and make that a condition alongside `<-timeoutCh` but the timer will still be `interval`+ the duration of the previous execution.

I'll propose you a change tomorrow to make it less buggy.

2024-11-11 19:28 UTC, patrickdappollonio commented on internal/download/download.go
> +	resp, err := http.Get(url)
It's fine to leave it as-is for now but this could potentially mean that a bad internet connection (and based on some of the support requests in our public slack, people seem to face them a lot especially with docker containers) would mean that whoever calls `FileFromURL` might wait forever without realizing the connection broke.

We **should never** use the Go standard library HTTP client (which is what you use when you use `http.Get()` and instead create our own with a timeout for header received or lack of bytes transferred, so we can surface that to users whenever they face problems instead of troubleshooting their internet connections.

2024-11-11 19:28 UTC, patrickdappollonio commented on internal/download/download.go
> +	// Copy returns err == nil..
Really! 😆 I doubt that if the connection breaks in the middle of a download! `:trollface:`.

2024-11-11 19:28 UTC, patrickdappollonio commented on internal/k8s/k8s.go
> +	c.logger.Debugf("created Secret %q in Namespace %q\n", s.Name, s.Namespace)
```suggestion
	c.logger.Debugf("created Secret %q in Namespace %q", s.Name, s.Namespace)
```

2024-11-11 19:28 UTC, patrickdappollonio commented on internal/k8s/k8s.go
> +	c.logger.Debugf("created Secret %q in Namespace %q\n", s.Name, s.Namespace)
```suggestion
	c.logger.Debugf("created Secret %q in Namespace %q", s.Name, s.Namespace)
```

2024-11-11 19:28 UTC, patrickdappollonio commented on internal/k8s/k8s.go
> +	log := logger.New(logger.Debug)
Seems the logger is still created here and not being used from the client.

2024-11-11 19:46 UTC, jarededwards commented on internal/docker/docker.go
> +	defer c.cli.Close()
I knew I hit resolved on something accidentally. Will start with this when I can!

2024-11-12 14:45 UTC, jarededwards commented on cmd/init.go
> +	cmd.Flags().StringVar(&loadBalancerInterface, "loadBalancerInterface", "eth0", "the local network interface for colony to use (required)")
i kept going with what was in place but have adjusted to posix style, i agree those flag names were harder to read

2024-11-14 15:56 UTC, patrickdappollonio approved these changes

2024-11-14 15:58 UTC, merged