fix: use objects's metadata.namespace when creating an object and add test
konstructio/colony pull request #8
Opened 2024-09-10 22:43 UTC by muse-sisay

## Description

## Related Issue(s)

Fixes #

## How to test

2024-09-11 00:45 UTC, patrickdappollonio commented on internal/k8s/k8s_test.go
> +		mockServer := fakeServer.NewClientset()
Nitpick: In Go, multiple declarations can be wrapped in this format:

```suggestion
var (
	secretNamespace = "tink-system"
	secretName      = "colony-api"
	secretKey       = "api-key"
	secretValue     = "super-duper-secret"

	mockServer = fakeServer.NewClientset()
)
```

Makes it nice to read 😄

2024-09-11 00:45 UTC, patrickdappollonio commented on internal/k8s/k8s.go
>  	dynamic    *dynamic.DynamicClient
Not to fix in this PR since we have probably a more challenging one to do, but I found out what `interface` replaces `dynamic.DynamicClient`: it is, you guessed it, `dynamic.Interface` 🤣

2024-09-13 14:06 UTC, johndietz submitted a review, later dismissed

2024-09-13 19:45 UTC, patrickdappollonio requested changes

2024-09-13 19:45 UTC, patrickdappollonio commented on internal/k8s/k8s_test.go
> +)
There seems to be some indentation problems, perhaps your `gofumpt` is not working 😢

2024-09-17 17:15 UTC, muse-sisay commented on internal/k8s/k8s_test.go
> +)
I guess so @patrickdappollonio :(. Thank you for pointing it out. Installed and pushed a commit.

2024-09-17 19:52 UTC, patrickdappollonio approved these changes

2024-09-18 03:14 UTC, merged